version: '3.8'

services:
  nginx_webserver:
    image: nginx:latest
    container_name: nginx_webserver
    ports:
      - "8080:80"
    networks:
      - nginx_bridge
    restart: always

  apache_webserver:
    image: httpd:latest
    container_name: apache_webserver
    ports:
      - "8081:80"
    networks:
      - apache_bridge
    restart: always

  nginx_load_balancer:
    image: nginx:latest
    container_name: nginx_load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - nginx_bridge
      - apache_bridge
    restart: always

networks:
  nginx_bridge:
    driver: bridge
  apache_bridge:
    driver: bridge
